var map_config = {
	'map_1':{
		'hover': 'ANDHRA PRADESH',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_2':{
		'hover': 'ARUNACHAL PRADESH',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_3':{
		'hover': 'ASSAM',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_4':{
		'hover': 'BIHAR',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_5':{
		'hover': 'CHHATTISGARH',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_6':{
		'hover': 'GOA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_7':{
		'hover': 'GUJARAT',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_8':{
		'hover': 'HARYANA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_9':{
		'hover': 'HIMACHAL PRADESH',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_10':{
		'hover': 'JAMMU AND KASHMIR',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_11':{
		'hover': 'JHARKHAND',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_12':{
		'hover': 'KARNATAKA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_13':{
		'hover': 'KERALA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_14':{
		'hover': 'MADHYA PRADESH',
		'upColor':'#e0f3ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_15':{
		'hover': 'MAHARASHTRA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_16':{
		'hover': 'MANIPUR',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_17':{
		'hover': 'MEGHALAYA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_18':{
		'hover': 'MIZORAM',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_19':{
		'hover': 'NAGALAND',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_20':{
		'hover': 'ODISHA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_21':{
		'hover': 'PUNJAB',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_22':{
		'hover': 'RAJASTHAN',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_23':{
		'hover': 'SIKKIM',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_24':{
		'hover': 'TAMIL NADU',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_25':{
		'hover': 'TELANGANA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_26':{
		'hover': 'TRIPURA',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_27':{
		'hover': 'UTTAR PRADESH',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_28':{
		'hover': 'UTTARAKHAND',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_29':{
		'hover': 'WEST BENGAL',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_30':{
		'hover': 'ANDAMAN AND NICOBAR ISLANDS',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_31':{
		'hover': 'CHANDIGARH',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_32':{
		'hover': 'DADRA AND NAGAR HAVELI',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_33':{
		'hover': 'DAMAN AND DIU',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_34':{
		'hover': 'LAKSHADWEEP',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_35':{
		'hover': 'NATIONAL CAPITAL TERRITORY OF DELHI',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	},
	'map_36':{
		'hover': 'PUDUCHERRY',
		'upColor':'#eff9ff',
		'overColor':'#ffcc5f',
		'downColor':'#477cb2',
		'enable':true,
	}
}

var defaultconf = {'borderColor':'#9CA8B6','mapShadow':'#fff','shadowOpacity':'50','hoverShadow':'#666666','namesColor':'#9CA8B6',};